version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: ["/bin/bash", "-c", "source /code/env/bin/activate && python ./www/manage.py runserver 0.0.0.0:8000"]
    volumes:
      - ./django:/code/www
    ports:
      - "8000:8000"
    depends_on:
      - db